## Example:

In [5]:
import pandas as pd

data = {
    'AAPL': [0.01, 0.02, -0.01, 0.00, 0.03],
    'GOOG': [0.02, 0.01, -0.02, 0.01, 0.04],
    'TSLA': [-0.01, 0.00, 0.01, -0.02, 0.05]
}

df = pd.DataFrame(data)

correlation = df.corr()
print(correlation)

from sklearn.linear_model import LinearRegression

X = df[['GOOG', 'TSLA']]  # predictors
y = df['AAPL']            # target

model = LinearRegression().fit(X, y)

print("Intercept:", model.intercept_)
print("Coefficients:", model.coef_)

          AAPL      GOOG      TSLA
AAPL  1.000000  0.875190  0.585206
GOOG  0.875190  1.000000  0.443877
TSLA  0.585206  0.443877  1.000000
Intercept: 0.002431941923774955
Coefficients: [0.55898367 0.14337568]

- Correlation says: “Do Apple and Google move together?”
- Regression says: “How much does Apple tend to move when Google or Tesla move?

A 1% increase in GOOG's return will yield in a 0.55% of AAPL, and a 1% increase in TSLA will yield 0.14% in AAPL.

In [6]:
df

   AAPL  GOOG  TSLA
0  0.01  0.02 -0.01
1  0.02  0.01  0.00
2 -0.01 -0.02  0.01
3  0.00  0.01 -0.02
4  0.03  0.04  0.05

## The Real Deal:

In [7]:
import yfinance as yf
tickers_list = ['MSFT', 'GOOG']
data = yf.download(tickers_list, start='2020-01-01', end='2021-01-01', interval = '1mo')['Close']

df = pd.DataFrame(data)
data

[*********************100%***********************]  2 of 2 completed

2 Failed downloads:
['GOOG', 'MSFT']: YFRateLimitError('Too Many Requests. Rate limited. Try after a while.')

Empty DataFrame
Columns: [GOOG, MSFT]
Index: []

In [9]:
correlation = df.corr()
print(correlation)

from sklearn.linear_model import LinearRegression

X = df[['MSFT']]  # predictors
y = df['GOOG']            # target

model = LinearRegression().fit(X, y)

print("Intercept:", model.intercept_)
print("Coefficients:", model.coef_)

Ticker  GOOG  MSFT
Ticker
GOOG     NaN   NaN
MSFT     NaN   NaN

ValueError: Found array with 0 sample(s) (shape=(0, 1)) while a minimum of 1 is required by LinearRegression.

1% increase in MSFT will result in 0.32% increase of GOOG